theme: jekyll-theme-minimal
title: Yeqing's homepage
description: braindump of Yeqing!
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
